---
  - hosts: workstation
    become: yes
    tasks:
      - name: install apache
        yum:
          name: httpd
          state: latest
      - name: start and enable httpd
        service:
          name: httpd
          state: started
          enabled: yes
      - name: create index.html
        file: 
          path: /var/www/html/index.html
          state: touch
      - name: add a line to index.html
        lineinfile:
          path: /var/www/html/index.html
          line: "<h1> Hello World !! this is a line added by ansible </h1>"



          
