---
-  hosts: local
   vars:
      inv_file: /home/ansible/red-Hat-Certified-Specialist-in-Ansible-Automation-Course/vars/inv.txt
   tasks:
   - name: create file
     file:
       path: "{{ inv_file }}"
       state: touch
   - name: generate inventory
     lineinfile:
       path: "{{ inv_file }}"
       line: "{{ groups['workstation']|join(' ') }}"
